# Generated by Django 2.2.6 on 2019-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
