# Generated by Django 2.2.6 on 2019-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
