# Generated by Django 2.2.6 on 2019-11-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20191104_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='profit',
        ),
    ]
