# Generated by Django 2.2.6 on 2019-11-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('league_name', models.CharField(max_length=70)),
                ('match_date', models.DateField()),
                ('match_status', models.CharField(max_length=50, null=True)),
                ('match_time', models.TimeField()),
                ('match_hometeam_name', models.CharField(max_length=70)),
                ('match_hometeam_score', models.IntegerField(null=True)),
                ('match_awayteam_name', models.CharField(max_length=70)),
                ('match_awayteam_score', models.IntegerField(null=True)),
                ('prob_HW', models.FloatField()),
                ('prob_D', models.FloatField()),
                ('prob_AW', models.FloatField()),
            ],
        ),
    ]
