# Generated by Django 2.2.6 on 2019-11-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('country_name', models.CharField(max_length=50)),
                ('league_name', models.CharField(max_length=70)),
                ('match_date', models.DateField()),
                ('match_status', models.CharField(max_length=50)),
                ('match_time', models.TimeField()),
                ('match_hometeam_name', models.CharField(max_length=70)),
                ('match_hometeam_score', models.IntegerField()),
                ('match_awayteam_name', models.CharField(max_length=70)),
                ('match_awayteam_score', models.IntegerField()),
                ('prob_HW', models.FloatField()),
                ('prob_D', models.FloatField()),
                ('prob_AW', models.FloatField()),
                ('winner', models.CharField(max_length=70)),
            ],
        ),
    ]
