# Generated by Django 2.2.6 on 2019-11-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
